### ISSUE TITLE
Result of cmds.total is too long to send

### ISSUE THREAD

**Issue by Asperger** [Asperger/PCRD-DiscordBot#3]
2019-07-31 01:29:09,834[INFO] 538023210864738314 call total with []
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python\Python36\lib\site-packages\discord\client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 30, in on_message
    await message.channel.send(msg)
  File "C:\Python\Python36\lib\site-packages\discord\abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Python\Python36\lib\site-packages\discord\http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 BAD REQUEST (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.

**Comment by Asperger** [comment]
use isinstance(msg, collections.Mapping) to check if the returned is a dictionary
isinstance(msg, list) to check list

**Comment by Asperger** [comment]
done
